# Generated by Django 4.0.4 on 2022-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-05-14 12:04:19.126780'),
        ),
    ]
